import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import SmoothScrollProvider from "./components/SmoothScrollProvider";
import "./globals.css";
import Navbar from "./components/Navbar";
import FooterSection from "./components/FooterSection";

const inter = Inter({ subsets: ["latin"] });
const customFont = localFont({
  src: "../public/fonts/OffBitTrial-DotBold.otf",
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  colorScheme: "light",
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScrollProvider>
      <html lang="en">
        <body
          className={`${inter.className} ${customFont.variable} bg-white text-brandText overflow-x-hidden`}
        >
          <Navbar />
          {children}
          <FooterSection />
        </body>
      </html>
    </SmoothScrollProvider>
  );
}
