import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import SmoothScrollProvider from "./components/SmoothScrollProvider";
import "./globals.css";
import Navbar from "./components/Navbar";
import FooterSection from "./components/FooterSection";

const inter = Inter({ subsets: ["latin"] });
const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gateway tech",
  description: "Generated by create next app",
};

export const viewport = {
  colorScheme: "light",
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScrollProvider>
      <html lang="en">
        <body
          className={`${dmSans.className} bg-white text-brandText overflow-x-hidden`}
        >
          <Navbar />
          {children}
          <FooterSection />
        </body>
      </html>
    </SmoothScrollProvider>
  );
}
